# NON GRADED CHALLENGE 4

### Problems
1. Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$


Jawaban:

In [9]:
from numpy import array
T = array([[[23,50], [7,12]], [[57,67], [99,43]], [[75,21], [57,12]], [[87,26], [18,84]]])
print(T)
print(T.shape)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]
(4, 2, 2)


2. Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  B =
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

Jawaban:

In [14]:
A = array([[23,50,19], [7,12,109], [57,67,98]])
B = array([[17],[22],[19]])
print(A @ B)

[[1852]
 [2454]
 [4305]]


3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$

In [16]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [22]:
from numpy.linalg import inv, det
inv_A = inv(A)
det_A = det(A)
print(f'''invers A adalah:
{inv_A} 
determinan A = {det_A}''')


invers A adalah:
[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]] 
determinan A = 131344.0000000002
